apiVersion: apps/v1
kind: Deployment
metadata:
  name: helidon-movie
  labels:
    commit: eda521cb1e97cfa7727b3e98ad0a5136bcb301e3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helidon-movie
  template:
    metadata:
      labels:
        app: helidon-movie
        commit: ${GIT_COMMIT}
        color: blue
    spec:
      containers:
      - name: helidon-movie
        image: ${DOCKER_REGISTRY}/${DOCKER_REPO}:eda521cb1e97cfa7727b3e98ad0a5136bcb301e3
        imagePullPolicy: Always
        ports:
        - name: helidon-movie
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: helidon-movie
  labels:
    app: helidon-movie
    commit: eda521cb1e97cfa7727b3e98ad0a5136bcb301e3
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: helidon-movie
    color: blue
  type: LoadBalancer
---
